### ISSUE TITLE
Enable the gutter behaviour

### ISSUE THREAD

**Issue by KarolAdamiec** [LightTable/JSHint#8]
I see there is inline and gutter variant for jshint, but i am unable to turn the gutter one on.
My config is:
[:editor.javascript :lt.plugins.jshint/on-change]
 [:editor.javascript :lt.plugins.jshint/gutter-hints]
 [:editor.javascript :-lt.plugins.jshint/inline-hints]
 
But that basically shows no feedback at all. The inline behaviour works if just left at default setting.

Is gutter supported still?

**Comment by cldwalker** [comment]
I'm able to see gutter hints with the latest LT and latest version of this plugin (just released). This was probably caused by gutter styling that been disabled in LT
